require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const path = require('path');

const authRoutes = require('./routes/auth.routes');
const companyRoutes = require('./routes/company.routes');
const notificationRoutes = require('./routes/notification.routes');
const experienceRoutes = require('./routes/experience.routes');
const studentRoutes = require('./routes/student.routes');
const { errorHandler } = require('./middleware/errorHandler');

const app = express();

const session = require('express-session');
const passport = require('./utils/passport');
const { generateTokens } = require('./controllers/authController');

// Session config
app.use(session({
  secret: process.env.SESSION_SECRET || 'placementhub_session_secret',
  resave: false,
  saveUninitialized: false
}));

app.use(passport.initialize());
app.use(passport.session());

// Google OAuth endpoints
app.get('/auth/google', (req, res, next) => {
  console.log('[OAuth Start] GET /auth/google hit.');
  const clientID = (process.env.GOOGLE_CLIENT_ID || '').trim();
  const clientSecret = (process.env.GOOGLE_CLIENT_SECRET || '').trim();
  const callbackURL = (process.env.GOOGLE_CALLBACK_URL || '').trim();
  console.log('[OAuth Start] GOOGLE_CLIENT_ID used at runtime:', clientID);
  console.log('[OAuth Start] GOOGLE_CALLBACK_URL used at runtime:', callbackURL);
  console.log('[OAuth Start] CLIENT_URL used at runtime:', process.env.CLIENT_URL);
  
  if (!clientID || !clientSecret) {
    const target = `${process.env.CLIENT_URL || 'http://localhost:5173'}/login?error=oauth_not_configured`;
    console.log('[OAuth Start] Credentials missing. Redirecting to redirect target:', target);
    return res.redirect(target);
  }

  // Intercept the redirect to capture the OAuth request URL generated by passport
  const originalRedirect = res.redirect;
  res.redirect = function (url) {
    console.log('[OAuth Start] Passport redirected browser to OAuth request URL:', url);
    res.redirect = originalRedirect; // restore
    return originalRedirect.apply(this, arguments);
  };

  console.log('[OAuth Start] Triggering passport.authenticate("google")...');
  passport.authenticate('google', { scope: ['profile', 'email'] })(req, res, next);
});

app.get('/auth/google/callback',
  (req, res, next) => {
    console.log('[OAuth Callback] GET /auth/google/callback hit (Callback URL).');
    console.log('[OAuth Callback] Full original URL:', req.originalUrl);
    console.log('[OAuth Callback] Host header:', req.headers.host);
    console.log('[OAuth Callback] Query parameters:', JSON.stringify(req.query));
    
    const clientID = (process.env.GOOGLE_CLIENT_ID || '').trim();
    const clientSecret = (process.env.GOOGLE_CLIENT_SECRET || '').trim();
    if (!clientID || !clientSecret) {
      const target = `${process.env.CLIENT_URL || 'http://localhost:5173'}/login?error=oauth_not_configured`;
      console.log('[OAuth Callback] Credentials missing. Redirecting to redirect target:', target);
      return res.redirect(target);
    }
    const failureTarget = `${process.env.CLIENT_URL || 'http://localhost:5173'}/login?error=oauth_failed`;
    console.log('[OAuth Callback] Triggering passport.authenticate("google") callback verification...');
    passport.authenticate('google', { 
      failureRedirect: failureTarget, 
      session: false 
    }, (err, user, info) => {
      console.log('[OAuth Callback] Passport callback execution triggered.');
      if (err) {
        console.error('[OAuth Callback] Passport verification error:', err);
        return res.redirect(failureTarget);
      }
      if (!user) {
        console.log('[OAuth Callback] Passport authentication failed. Info:', info);
        return res.redirect(failureTarget);
      }
      console.log('[OAuth Callback] Passport authentication success! Logged-in User:', user.email);
      req.user = user;
      next();
    })(req, res, next);
  },
  async (req, res) => {
    try {
      console.log('[OAuth Callback Success] Generating tokens for user:', req.user ? req.user.email : 'undefined');
      const { accessToken, refreshToken } = generateTokens(req.user);
      const userService = require('./services/userService');
      await userService.updateRefreshToken(req.user.id, refreshToken);
      const target = `${process.env.CLIENT_URL || 'http://localhost:5173'}/login?token=${accessToken}&refreshToken=${refreshToken}`;
      console.log('[OAuth Callback Success] Redirecting user to frontend target (Redirect target):', target);
      res.redirect(target);
    } catch (err) {
      console.error('[OAuth Callback Success Error] Google OAuth callback error:', err.message);
      const target = `${process.env.CLIENT_URL || 'http://localhost:5173'}/login?error=oauth_error`;
      console.log('[OAuth Callback Success Error] Redirecting user to redirect target:', target);
      res.redirect(target);
    }
  }
);

// ─── Security & Middleware ───────────────────────────────
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({
  origin: process.env.CLIENT_URL || 'http://localhost:5173',
  credentials: true,
}));
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));

// ─── Static file serving (uploads) ──────────────────────
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

// ─── Health Check ────────────────────────────────────────
app.get('/api/health', (req, res) => {
  res.json({ success: true, message: 'CRMS API is running', timestamp: new Date().toISOString() });
});

// ─── SMTP Email Test Endpoint ────────────────────────────
app.get('/api/test-email', async (req, res) => {
  try {
    const { sendPasswordResetEmail } = require('./services/emailService');
    console.log("[Test Email Endpoint] Triggering sendPasswordResetEmail test...");
    
    const testRecipient = req.query.email || process.env.SMTP_USER || "bharathkumaryadla@gmail.com";
    console.log("[Test Email Endpoint] Sending to:", testRecipient);
    
    const info = await sendPasswordResetEmail({
      to: testRecipient,
      userName: "Test User",
      resetUrl: "https://placementhub-lake.vercel.app/reset-password?token=testtoken123"
    });
    
    res.json({
      success: true,
      message: "Test email dispatched successfully!",
      info
    });
  } catch (err) {
    console.error("[Test Email Endpoint] Failed:", err);
    res.status(500).json({
      success: false,
      message: "SMTP Test Failed",
      error: {
        message: err.message,
        code: err.code,
        command: err.command,
        response: err.response,
        responseCode: err.responseCode,
        stack: err.stack
      }
    });
  }
});

// ─── Routes ──────────────────────────────────────────────
app.use('/api/auth', authRoutes);
app.use('/api/companies', companyRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/experiences', experienceRoutes);
app.use('/api/users', studentRoutes);

// ─── 404 Handler ─────────────────────────────────────────
app.use('*', (req, res) => {
  res.status(404).json({ success: false, message: `Route ${req.originalUrl} not found` });
});

// ─── Global Error Handler ─────────────────────────────────
app.use(errorHandler);

// ─── Start Server ─────────────────────────────────────────
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`\n🚀 CRMS Server running on http://localhost:${PORT}`);
  console.log(`📖 Environment: ${process.env.NODE_ENV || 'development'}`);
  
  let dbLogString = '';
  if (process.env.DATABASE_URL) {
    try {
      const parsed = new URL(process.env.DATABASE_URL.trim());
      dbLogString = `${parsed.pathname.replace('/', '')} @ ${parsed.hostname} (via DATABASE_URL)`;
    } catch (e) {
      dbLogString = 'Neon/Remote Database (via DATABASE_URL)';
    }
  } else {
    dbLogString = `${process.env.DB_NAME || 'crms_db'} @ ${process.env.DB_HOST || 'localhost'}`;
  }
  console.log(`🗄️  Database: ${dbLogString}\n`);
});

module.exports = app;
